clusterName: "elasticsearch"
antiAffinity: "soft"

# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "2"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "1Gi"

esJvmOptions:
  jvm.options: |
    -Xms1g
    -Xmx4g
# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 100M
extraEnvs: 
 - name: OTEL_SERVICE_NAME
   value: "elasticsearch-service"
 - name: OTEL_SERVICE_NAMESPACE
   value: "observability"
 - name: OTEL_SERVICE_VERSION
   value: "1.0.0"
 - name: xpack.security.enabled
   value: "false"
 - name: xpack.security.http.ssl.enabled
   value: "false"
 - name: xpack.security.transport.ssl.enabled
   value: "false"
 - name: xpack.security.http.ssl.client_authentication
   value: "none"
#  - name: discovery.type
#    value: "single-node"

protocol: http
esJvmOptions:
  jvm.options: |
    -Djava.security.manager 
    -Djava.security.policy=/usr/share/elasticsearch/config/policy.file
    -Xms4g
    -Xmx4g

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false  
    xpack.security.http.ssl.client_authentication: none  

networkPolicy:
  http:
    enabled: false   # This means HTTP traffic is not filtered, unless you plan to enable specific access control
  transport:
    enabled: false   # This means transport traffic (internal Elasticsearch node communication) is not restricted

extraVolumes:
  - name: security-policy
    configMap:
      name: security-policy-config

extraVolumeMounts:
  - name: security-policy
    mountPath: /usr/share/elasticsearch/config/policy.file
    subPath: policy.file



# resources:
#   requests:
#     cpu: "4"
#     memory: "6Gi"
#   limits:
#     cpu: "4"
#     memory: "6Gi"

# volumeClaimTemplate:
#   accessModes: [ "ReadWriteOnce" ]
#   storageClassName: "standard"
#   resources:
#     requests:
#       storage: 100M

# extraVolumes:
#   - name: security-policy
#     configMap:
#       name: security-policy-config

# extraVolumeMounts:
#   - name: security-policy
#     mountPath: /usr/share/elasticsearch/config/policy.file
#     subPath: policy.file

# extraEnvs: 
#  - name: OTEL_SERVICE_NAME
#    value: "elasticsearch-service"
#  - name: OTEL_SERVICE_NAMESPACE
#    value: "observability"
#  - name: OTEL_SERVICE_VERSION
#    value: "1.0.0"
  

