allInOne:
  enabled: false  

storage:
  type: elasticsearch  
  elasticsearch:
    host: elasticsearch-master
    port: 9200
    scheme: http
    usePassword: true
    user: elastic
    password: changeme

collector:
  enabled: false  

query:
  enabled: true 
  resources:
    requests:
      memory: "400Mi"
      cpu: "200m"
    limits:
      memory: "800Mi"
      cpu: "400m"

agent:
  enabled: false

provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false