apiVersion: operator.dash0.com/v1alpha1
kind: Dash0Monitoring
metadata:
  name: dash0-monitoring-resource
spec:
  instrumentWorkloads: all
  synchronizePersesDashboards: false
  synchronizePrometheusRules: false
  prometheusScrapingEnabled: false
